# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ development ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ development, main ]
    paths-ignore:
      - '*.md'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Decode API KEY
        env:
          API_KEY: ${{secrets.API_KEY}}
          FIREBASE_KEY: ${{secrets.FIREBASE_KEY}}
        run: |
          echo $FIREBASE_KEY > app/google-services.json
          echo $API_KEY > gradle.properties
          echo "org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8" >> gradle.properties
          echo "android.useAndroidX=true" >> gradle.properties
          echo "android.enableJetifier=true" >> gradle.properties
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
